# Use NVIDIA CUDA runtime as parent image
FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app
RUN chmod 777 /app
ENV PYTHONPATH="/app"

# Install system dependencies & Python 3.11
RUN apt-get update && apt-get install -y --no-install-recommends \
        software-properties-common \
        git \
        ffmpeg \
        curl \
        && add-apt-repository ppa:deadsnakes/ppa \
        && apt-get update && apt-get install -y --no-install-recommends \
        python3.11 \
        python3.11-venv \
        python3.11-dev \
        python3-pip \
        && ln -sf /usr/bin/python3.11 /usr/bin/python3 \
        && ln -sf /usr/bin/python3.11 /usr/bin/python \
        && python3.11 -m pip install --upgrade pip \
        && rm -rf /var/lib/apt/lists/*

# Copy requirements
COPY requirements.txt ./

# Install Python dependencies
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Copy codebase
COPY . .

# Expose API & Studio port
EXPOSE 8080

# Start Chronus FastAPI application
CMD ["python3", "main.py"]
